// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW7ZU0YvR3BefV5RoVsK6-H7AtakUwNQw',
    appId: '1:850795189571:web:6cf63cb1ec9d62f8a70bf6',
    messagingSenderId: '850795189571',
    projectId: 'mobileapp-final-22101046',
    authDomain: 'mobileapp-final-22101046.firebaseapp.com',
    storageBucket: 'mobileapp-final-22101046.firebasestorage.app',
    measurementId: 'G-RP0QMKSMS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoVq5WubFiCOoYBLjQp_MAMctPT7Dc6-w',
    appId: '1:850795189571:android:a50750d0edd8907fa70bf6',
    messagingSenderId: '850795189571',
    projectId: 'mobileapp-final-22101046',
    storageBucket: 'mobileapp-final-22101046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LMuZRsZlbDH-vKvLPjGhq6c1z5nXOp4',
    appId: '1:850795189571:ios:f3c7f8a81509c181a70bf6',
    messagingSenderId: '850795189571',
    projectId: 'mobileapp-final-22101046',
    storageBucket: 'mobileapp-final-22101046.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6LMuZRsZlbDH-vKvLPjGhq6c1z5nXOp4',
    appId: '1:850795189571:ios:f3c7f8a81509c181a70bf6',
    messagingSenderId: '850795189571',
    projectId: 'mobileapp-final-22101046',
    storageBucket: 'mobileapp-final-22101046.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW7ZU0YvR3BefV5RoVsK6-H7AtakUwNQw',
    appId: '1:850795189571:web:fa0c338caab79034a70bf6',
    messagingSenderId: '850795189571',
    projectId: 'mobileapp-final-22101046',
    authDomain: 'mobileapp-final-22101046.firebaseapp.com',
    storageBucket: 'mobileapp-final-22101046.firebasestorage.app',
    measurementId: 'G-2VMEX4XSH0',
  );

}