// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWIi-SWYk3r5xX14aSw6Uh_G-2QUqygWM',
    appId: '1:241632718216:web:5ea8e181c46d83ef635e3d',
    messagingSenderId: '241632718216',
    projectId: 'god-speak-ai',
    authDomain: 'god-speak-ai.firebaseapp.com',
    databaseURL: 'https://god-speak-ai-default-rtdb.firebaseio.com',
    storageBucket: 'god-speak-ai.firebasestorage.app',
    measurementId: 'G-N01ZWWFPES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG3fh2O2nnk1sB1_qL8eBc91miqDGj420',
    appId: '1:241632718216:android:f75aa23a9b1c0b11635e3d',
    messagingSenderId: '241632718216',
    projectId: 'god-speak-ai',
    databaseURL: 'https://god-speak-ai-default-rtdb.firebaseio.com',
    storageBucket: 'god-speak-ai.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkb2J9_A0v2ujeNkvn8K8byaBeoLNhMzw',
    appId: '1:241632718216:ios:71ed0f3ee6c09a3e635e3d',
    messagingSenderId: '241632718216',
    projectId: 'god-speak-ai',
    databaseURL: 'https://god-speak-ai-default-rtdb.firebaseio.com',
    storageBucket: 'god-speak-ai.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFinal',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkb2J9_A0v2ujeNkvn8K8byaBeoLNhMzw',
    appId: '1:241632718216:ios:71ed0f3ee6c09a3e635e3d',
    messagingSenderId: '241632718216',
    projectId: 'god-speak-ai',
    databaseURL: 'https://god-speak-ai-default-rtdb.firebaseio.com',
    storageBucket: 'god-speak-ai.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWIi-SWYk3r5xX14aSw6Uh_G-2QUqygWM',
    appId: '1:241632718216:web:433607dc0306e842635e3d',
    messagingSenderId: '241632718216',
    projectId: 'god-speak-ai',
    authDomain: 'god-speak-ai.firebaseapp.com',
    databaseURL: 'https://god-speak-ai-default-rtdb.firebaseio.com',
    storageBucket: 'god-speak-ai.firebasestorage.app',
    measurementId: 'G-ZN7FZ91JJ9',
  );
}
