// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRmFDe2k8TO8sSmjVoGgLaHf_SxNWVBSg',
    appId: '1:693235051503:web:3cdb8f06baa7d316b8a41a',
    messagingSenderId: '693235051503',
    projectId: 'mobile-app-final-22101046',
    authDomain: 'mobile-app-final-22101046.firebaseapp.com',
    storageBucket: 'mobile-app-final-22101046.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS0CXKroQ_zYjcfX_by5-bfnjBHwBbekw',
    appId: '1:693235051503:android:829160e7605f067eb8a41a',
    messagingSenderId: '693235051503',
    projectId: 'mobile-app-final-22101046',
    storageBucket: 'mobile-app-final-22101046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05jklb-2VJtGIRu4nBhl3bXqUfWCfgOU',
    appId: '1:693235051503:ios:b2743f68993679cab8a41a',
    messagingSenderId: '693235051503',
    projectId: 'mobile-app-final-22101046',
    storageBucket: 'mobile-app-final-22101046.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05jklb-2VJtGIRu4nBhl3bXqUfWCfgOU',
    appId: '1:693235051503:ios:b2743f68993679cab8a41a',
    messagingSenderId: '693235051503',
    projectId: 'mobile-app-final-22101046',
    storageBucket: 'mobile-app-final-22101046.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRmFDe2k8TO8sSmjVoGgLaHf_SxNWVBSg',
    appId: '1:693235051503:web:baaccf71eb67f299b8a41a',
    messagingSenderId: '693235051503',
    projectId: 'mobile-app-final-22101046',
    authDomain: 'mobile-app-final-22101046.firebaseapp.com',
    storageBucket: 'mobile-app-final-22101046.firebasestorage.app',
  );
}
